#!/bin/sh

function has {
  opam config var "${1}:installed"
}

topkg build -- \
  --with-mirage-unix $(has 'mirage-unix') \
  --with-mirage-xen $(has 'mirage-xen') \
  --with-mirage-solo5 $(has 'mirage-solo5')
